---
config:
  theme: redux
---
flowchart TD
 subgraph planner["planner"]
        replan["Update Plan (o3-mini)"]
        next{"Select Next Task (o3-mini)"}
        ptt["Pentest Task Tree"]
  end
 subgraph executor["executor"]
        execute["Perform Task (gpt-4o)"]
        execute_decide{"Tool or Finished?"}
        tool_call["tool_call"]
        shell_history["Episodic Shell History"]
        message_history["Episodic Message History"]
  end
    start(("Start")) -- "plan=None,task=None,summary='',knowledge='',leads=[]" --> replan
    replan <-. plan .-> ptt
    ptt -. plan .-> next
    replan --> next
    next -- task, context --> execute
    next --> finish((("done")))
    next -. task, context .-> summarizer["Summarizer (o3-mini)"] & replan
    execute --> execute_decide
    execute_decide -- cmd --> tool_call
    tool_call -- shell output --> execute_decide
    execute_decide -- result --> summarizer
    summarizer -. summary, vulnerabilities, leads .-> replan
    findings["Target Environment Knowlege"] -. knowledge .-> execute & replan & next
    execute_decide <-. cmd, cmd output .-> message_history
    execute_decide -. cmd, cmd output .-> shell_history
    shell_history -. cmd, cmd_output .-> summarizer
    summarizer -- new knowledge, vulnerabilities --> update_knowledge["Update Knowledge (o3-mini)"]
    summarizer -. leads .-> next
    update_knowledge <-. knowledge .-> findings
    update_knowledge --> replan
    ptt@{ shape: lin-cyl}
    tool_call@{ shape: procs}
    shell_history@{ shape: lin-cyl}
    message_history@{ shape: lin-cyl}
    findings@{ shape: lin-cyl}
