import asyncssh

from asyncssh import SSHClientConnection, SSHCompletedProcess
from dataclasses import dataclass
from common import get_or_fail

@dataclass
class SSHConnection:
    host: str = 'localhost'
    username: str = 'changeme'
    password: str = 'changeme'
    port: int = 22
    timeout: int = 600

    _conn: SSHClientConnection = None

    async def connect(self):
        self._conn = await asyncssh.connect(self.host, port=self.port, username=self.username, password=self.password, known_hosts=None)

    async def run(self, cmd) -> SSHCompletedProcess:
        if self._conn is None:
            raise Exception("SSH Connection not established")

        return await self._conn.run(cmd, timeout=self.timeout, stderr=asyncssh.STDOUT)
    
    async def execute_command(self, command: str, mitre_attack_technique: str, mitre_attack_procedure: str) -> str:
        """Execute a command over SSH and return the output.

        Parameters
        ----------
        command : str
            The command to execute.
        
        mitre_attack_technique : str
            The MITRE ATT&CK technique associated with the command.

        mitre_attack_procedure : str
            The MITRE ATT&CK procedure associated with the command.

        Returns
        -------
        str
            The output of the executed command.
        """
        if self._conn is None:
            raise Exception("SSH Connection not established")
        
        try:
            return (await self._conn.run(command, timeout=self.timeout, stderr=asyncssh.STDOUT)).stdout
        except asyncssh.process.TimeoutError as e:
            return f"""Timeout during command execution over SSH command execution.
The command will be stopped, if files have been generated by the command they will be left on the system.

The output so far was:

```bash
{e.stdout}
```"""
    
def get_ssh_connection_from_env() -> SSHConnection:
    host = get_or_fail("TARGET_HOST")
    username = get_or_fail("TARGET_USERNAME")
    password = get_or_fail("TARGET_PASSWORD")

    return SSHConnection(host=host, username=username, password=password)
